name: Organize Solyn Files

on:
  push:
    branches: [main]

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run organizer script
        run: python organize_files.py

      - name: Commit organized files
        run: |
          git config --global user.name "solyn-bot"
          git config --global user.email "solyn@auto.io"
          git add .
          git commit -m "Auto-organized structure" || echo "No changes"
          git push
